### ISSUE TITLE
falloutrain can cause CRASH ⚠⚠⚠

### ISSUE THREAD

**Issue by anonymousomeone** [Apethesis/HBM-Refurbished-OLD#3]
[crash-2024-10-21_21.00.37-server.txt](https://github.com/user-attachments/files/17467555/crash-2024-10-21_21.00.37-server.txt)

**Comment by anonymousomeone** [comment]
`[12:28:53] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201) ~[awu$a.class:?]
	at net.minecraft.block.BlockOldLeaf.getSaplingDropChance(BlockOldLeaf.java:45) ~[asn.class:?]
	at net.minecraft.block.BlockLeaves.getDrops(BlockLeaves.java:261) ~[arr.class:?]
	at net.minecraft.block.Block.getDrops(Block.java:1300) ~[aow.class:?]
	at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:571) ~[aow.class:?]
	at net.minecraft.block.BlockLeaves.dropBlockAsItemWithChance(BlockLeaves.java:209) ~[arr.class:?]
	at net.minecraft.block.Block.dropBlockAsItem(Block.java:564) ~[aow.class:?]
	at net.minecraft.block.BlockLeaves.destroy(BlockLeaves.java:181) ~[arr.class:?]
	at net.minecraft.block.BlockLeaves.updateTick(BlockLeaves.java:173) ~[arr.class:?]
	at net.minecraft.block.Block.randomTick(Block.java:508) ~[aow.class:?]
	at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476) ~[oo.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more`

**Comment by anonymousomeone** [comment]
see https://github.com/Apethesis/HBM-Refurbished/blob/main/src/main/java/com/hbm/entity/effect/EntityFalloutRain.java & related
