### ISSUE TITLE
Volcano causes immense player and server lag

### ISSUE THREAD

**Issue by Apethesis** [Apethesis/HBM-Refurbished-OLD#8]
A regular (not too large) volcano can cause immense server and client lag when the chunks of it are loaded.

**Comment by anonymousomeone** [comment]
```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at net.minecraft.world.chunk.Chunk.getEntitiesWithinAABBForEntity(Chunk.java:920)
    at net.minecraft.world.World.getEntitiesInAABBexcluding(World.java:3028)
    at net.minecraft.world.World.getEntitiesWithinAABBExcludingEntity(World.java:3011)
    at net.minecraft.entity.projectile.EntityThrowable.TickCentral_TrueOnUpdateTick(EntityThrowable.java:185)
    at com.hbm.entity.projectile.EntityShrapnel.TickCentral_TrueOnUpdateTick(EntityShrapnel.java:49)
    at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
    at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:105)
    at com.hbm.entity.projectile.EntityShrapnel.onUpdate(EntityShrapnel.java)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by anonymousomeone** [comment]
https://github.com/WangTingZheng/mcp940/blob/master/src/minecraft/net/minecraft/entity/projectile/EntityThrowable.java
